builds:
  - main: cameraSort.go
    binary: cameraSort
    goos:
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - main: listLargeDirs.go
    binary: listLargeDirs
    goos:
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
        
  - main: rmOldCamera.go
    binary: rmOldCamera
    goos:
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
