env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod tidy
    - test/APPIP01WV4_sort/test.sh
    - test/CNETCAM_sort/test.sh
    - test/generic_listLargeDirs/test.sh
    - test/generic_rmOldCameraData/test.sh
    - test/OWIPCAM4X_fetchImage/test.sh

builds:
  - id: APPIP01WV4_sort
    main: ./cmd/APPIP01WV4_sort
    binary: bin/APPIP01WV4_sort
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: CNETCAM_sort
    main: ./cmd/CNETCAM_sort
    binary: bin/CNETCAM_sort
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: generic_listLargeDirs
    main: ./cmd/generic_listLargeDirs
    binary: bin/generic_listLargeDirs
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: generic_recordVideo
    main: ./cmd/generic_recordVideo
    binary: bin/generic_recordVideo
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: generic_rmOldCameraData
    main: ./cmd/generic_rmOldCameraData
    binary: bin/generic_rmOldCameraData
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: OWIPCAM4X_fetchImage
    main: ./cmd/OWIPCAM4X_fetchImage
    binary: bin/OWIPCAM4X_fetchImage
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: OWIPCAM45_fetchVideo
    main: ./cmd/OWIPCAM45_fetchVideo
    binary: bin/OWIPCAM45_fetchVideo
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: OWIPCAM45_rotate
    main: ./cmd/OWIPCAM45_rotate
    binary: bin/OWIPCAM45_rotate
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

archives:
  - id: default
    builds:
      - APPIP01WV4_sort
      - CNETCAM_sort
      - generic_listLargeDirs
      - generic_rmOldCameraData
      - OWIPCAM4X_fetchImage
      - OWIPCAM45_fetchVideo
      - OWIPCAM45_rotate

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    format: tar.gz
