env_files:
  github_token: ~/.config/goreleaser/github_token
builds:
  - id: cameraSort
    main: ./cmd/cameraSort
    binary: bin/cameraSort
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: generic_listLargeDirs
    main: ./cmd/generic_listLargeDirs
    binary: bin/listLargeDirs
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: generic_rmOldCameraData
    main: ./cmd/generic_rmOldCameraData
    binary: bin/rmOldCameraData
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: fetchImage
    main: ./cmd/fetchImage
    binary: bin/fetchImage
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: OWIPCAM45_fetchVideo
    main: ./cmd/OWIPCAM45_fetchVideo
    binary: bin/OWIPCAM45_fetchVideo
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
  - id: OWIPCAM45_rotate
    main: ./cmd/OWIPCAM45_rotate
    binary: bin/OWIPCAM45_rotate
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: APPIP01WV4_sort
    main: ./cmd/APPIP01WV4_sort
    binary: bin/APPIP01WV4_sort
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

archive:
  format: tar.gz
