builds:
  - main: cmd/cameraSort/cameraSort.go
    binary: bin/cameraSort
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - main: cmd/listLargeDirs/listLargeDirs.go
    binary: bin/listLargeDirs
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
        
  - main: cmd/rmOldCamera/rmOldCamera.go
    binary: bin/rmOldCamera
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - main: cmd/fetchImage/fetchImage.go
    binary: bin/fetchImage
    ldflags: -X github.com/Miguel-Dorta/surveillance-cameras/internal.Version={{.Version}}
    goos:
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
